server:
  port: 8091
  servlet:
    context-path: "/api"
spring:
  datasource:
    hikari:
      max-lifetime: 180
      connection-timeout: 30000
    FE:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.3.221:5432/femanagement?useSSL=false
      username: postgres
      password: pgSiemens2o2o
    BF:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.3.221:5432/stcl_order_entry_db?useSSL=false
#      url: jdbc:postgresql://192.168.3.221:5432/stcl_order_entry_db?useSSL=false
      username: postgres
      password: pgSiemens2o2o

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
