server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:mapper/*.xml
