server:
  port: 8080

spring:
  datasource:
    FE:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
      username: postgres
      password: postgres
    BF:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://58.49.121.174:5432/stcl_order_entry_db?useSSL=false
      username: postgres
      password: pgSiemens2o2o

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
